---
- name: install redmine packages
  apt:
    name:
      - ruby
      - ruby-dev
      - ruby-bundler
      - imagemagick
      - libmagickwand-dev
      - libmysqlclient-dev
    state: latest
    update_cache: true
    cache_valid_time: 21600 # six hours
  become: true
- name: install gems
  gem:
    name: bundler
    state: latest
