- name: update buildkit tools
  shell: ./bin/civi-download-tools
  args:
    chdir: ~/src/civicrm-buildkit
- name: restart php7.0-fpm
  service:
    name: php7.0-fpm
    state: restarted
  become: true
