---
- name: provision master backup server
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
  - include: ec2-provision-instance.yml
    vars:
      role: backup_master
      host: backup-master
      private_ip: "{{ prips.backup_master }}"
      instance_type: t2.nano
      access: private
      az: a
      security_groups:
      - backup
      volumes:
      - device_name: /dev/sda1
        volume_size: 8
        volume_type: gp2
      - device_name: /dev/sdf
        volume_size: 500
        volume_type: sc1
- name: configure master backup server
  hosts: tag_role_backup_master
  roles:
  - { role: common, host: backup-master }
  - { role: user, users: [ { name: remote_backup, sudo: true, system: true }, {name: root } ] }
  - backup_master
