---
- name: provision master backup server
  hosts: localhost
  connection: local
  tasks:
  - include: ec2-provision.yml
    vars:
      count: 1
      instance_type: t2.nano
      availability_zone: a
      role: backup_master
  - meta: refresh_inventory

- name: configure master backup server
  hosts: tag_role_backup_master
  roles:
    - backup_master
    - backup_common
