---
- name: provision bastion host
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
  - include: ec2-provision-instance.yml
    vars:
      role: bastion
      host: bastion
      private_ip: "{{ prips.bastion }}"
      instance_type: t2.nano
      codename: trusty
      access: public
      az: a
      security_groups:
      - bastion







- name: configure bastion
  hosts: tag_role_bastion
  roles:
  - { role: common, host: bastion }
  - { role: user, users: [{name: remote_backup, sudo: true, system: true}] }
  - bastion
