- name: ensure public keys are present on hosts
  hosts: michael_laptop
  vars:
    keys:
    - host: backup-master.3sd.ec2
      user: remote_backup
      key: xps13.remote_backup
    - host: bastion.3sd.ec2
      user: remote_backup
      key: xps13.remote_backup

    hosts:
    - host: backup-master.3sd.ec2
      path: /root/.ssh/known_hosts
      known_host_key: xps13
      known_host: "[localhost]:30121"
    - host: backup-master.3sd.ec2
      path: /root/.ssh/known_hosts
      known_host_key: prod
      known_host: prod.thirdsectordesign.org
    - host: michael_laptop
      path: /home/remote_backup/.ssh/known_hosts
      known_host_key: backup-master
      known_host: backup-master.3sd.ec2
    - host: michael_laptop
      path: /home/remote_backup/.ssh/known_hosts
      known_host: bastion.thirdsectordesign.org
      known_host_key: bastion

  tasks:
  - authorized_key:
      user: "{{ item.user }}"
      key: "{{ lookup('file', '/srv/infra/ansible/vault/public_keys/{{ item.key }}.pub') }}"
    delegate_to: "{{ item.host }}"
    with_items: "{{ keys }}"
    become: true

  - known_hosts:
      path: "{{ item.path }}"
      name: "{{ item.known_host }}"
      key:  "{{ item.known_host }} {{ lookup('file', '/srv/infra/ansible/vault/public_keys/{{ item.known_host_key }}.ssh.pub') }}"
    delegate_to: "{{ item.host }}"
    with_items: "{{ hosts }}"
    become: true
