- name: ensure public keys are present on hosts
  hosts: michael_laptop
  vars:
    keys:
    - host: backup-master.3sd.ec2
      user: remote_backup
      key: xps13.remote_backup
    - host: bastion.3sd.ec2
      user: remote_backup
      key: xps13.remote_backup
    hosts:
    - host: backup-master.3sd.ec2
      path: /root/.ssh/known_hosts
      known_host: xps13
      known_host_reversed: "[localhost]:30121"
    - host: backup-master.3sd.ec2
      path: /root/.ssh/known_hosts
      known_host: prod
      known_host_reversed: "prod.thirdsectordesign.org"

  tasks:
  - authorized_key:
      user: "{{ item.user }}"
      key: "{{ lookup('file', '/srv/infra/ansible/vault/public_keys/{{ item.key }}.pub') }}"
    delegate_to: "{{ item.host }}"
    with_items: "{{ keys }}"
    become: true
  - known_hosts:
      path: "{{ item.path }}"
      name: "{% if item.known_host_reversed is defined %}{{ item.known_host_reversed }}{% else %}{{ item.known_host }}{% endif %}"
      key:  "{% if item.known_host_reversed  is defined %}{{ item.known_host_reversed }}{% else %}{{ item.known_host }}{% endif %} {{ lookup('file', '/srv/infra/ansible/vault/public_keys/{{ item.known_host }}.ssh.pub') }}"
    delegate_to: "{{ item.host }}"
    with_items: "{{ hosts }}"
    become: true
