---
- name: wait for SSH to come up on instance {{ item.id }} ({{ item.public_ip }})
  wait_for: port=22 host={{ item.public_ip }} search_regex=OpenSSH

- name: look up host key in console output
  shell: aws ec2 get-console-output --instance-id {{ item.id }} --output text|sed -n 's/ecdsa-sha2-nistp256 \([^ ]*\).*/\1/p'
  register: host_key
  until: host_key.stdout|length
  delay: 30
  retries: 30

- name: add host key to known_hosts
  known_hosts:
    name: "{{ item.public_ip }}"
    key: "{{ item.public_ip }} ecdsa-sha2-nistp256 {{ host_key.stdout }}"
    state: present
