---
- name: get host key in EC2 console output
  shell: aws ec2 get-console-output --instance-id {{ item.id }} --output text|sed -n 's/ecdsa-sha2-nistp256 \([^ ]*\).*/\1/p'
  register: host_key
  until: host_key.stdout|length
  delay: 30
  retries: 30
- name: add private ip to known_hosts
  known_hosts:
    name: "{{ item.private_ip }}"
    key: "{{ item.private_ip }} ecdsa-sha2-nistp256 {{ host_key.stdout }}"
- name: add private domain name to known_hosts
  known_hosts:
    name: "{{ host }}.{{ private_domain }}"
    key: "{{ host }}.{{ private_domain }} ecdsa-sha2-nistp256 {{ host_key.stdout }}"
- name: add public ip to known_hosts
  known_hosts:
    name: "{{ item.public_ip }}"
    key: "{{ item.public_ip }} ecdsa-sha2-nistp256 {{ host_key.stdout }}"
  when: access == 'public'
- name: add public domain name to known_hosts 
  known_hosts:
    name: "{{ host }}.{{ public_domain }}"
    key: "{{ host }}.{{ public_domain }} ecdsa-sha2-nistp256 {{ host_key.stdout }}"
  when: access == 'public'
# - name: wait for ssh (public network)
#   wait_for:
#     host: "{{ host }}.{{ public_domain }}"
#     port: 22
#     search_regex: OpenSSH
#   when: host == 'bastion'
# - name: wait for ssh (private network)
#   wait_for:
#     host: "{{ host }}.{{ private_domain }}"
#     port: 22
#     search_regex: OpenSSH
#   when: host != 'bastion'
