---
- name: configure legacy prod server
  hosts: legacy_prod_server
  vars:
    backup_mysql: true
    backup_paths:
    - source: /etc
    - source: /var
    - source: /srv
      excludes:
      - backup
    - source: /home/*
    - source: /root
    - source: /usr/local
  roles:
  - backed_up
  tasks:
  - name: cache ssh server public key
    fetch:
      src: /etc/ssh/ssh_host_ecdsa_key.pub
      dest: /srv/infra/ansible/vault/public_keys/prod.ssh.pub
      flat: true
