---
- name: configure my laptop
  hosts: michael_laptop
  connection: local
  vars:
    host: xps13
    fq_host: xps13
    backup_mysql: true
    backup_paths:
    - source: /etc
    - source: /var
      excludes:
      - "lib/mysql"
    - source: /srv
      excludes:
      - backup
    - source: /home
      excludes:
      - "*/.thunderbird"
      - "*/.gnupg"
      - "*/VirtualBox\\ VMs"
      - "*/.cache"
      - "*/Videos"
      - "*/.local/share/Trash"
      - "michael/Reference/disk-images"
    - source: /root
    - source: /usr/local
  roles:
  - controller
  - { role: backed_up, via_ssh_tunnel: true, ssh_tunnel_port: 30121 }
  - dev
  - node
  tasks:
  - hostname: name=xps13
    become: yes
