---
- name: provision production server
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
  - include: ec2-provision-instance.yml
    vars:
      role: production
      host: production
      codename: trusty
      private_ip: "{{ prips.production }}"
      instance_type: t2.small
      access: public
      az: a
      security_groups:
      - production
      volumes:
      - device_name: /dev/sda1
        volume_size: 20
        volume_type: gp2
- name: configure production server
  hosts: tag_role_production
  vars:
    backup_mysql: true
    backup_paths:
    - source: /etc
    - source: /var
    - source: /srv
      excludes:
      - backup
    - source: /home/*
    - source: /root
    - source: /usr/local
  roles:
  - { role: common, host: production }
  - { role: user, users: [ { name: remote_backup, sudo: true, system: true }, {name: root } ] }
  - mysql
  - backed_up
