---
- hosts: localhost
  name: Provision hosts if necessary
  connection: local
  gather_facts: False
  tasks:
  - name: Create an EC2 instance
    ec2:
      region: eu-central-1
      instance_type: t2.nano
      zone: eu-central-1a
      wait: yes
      image: ami-4bd03b24
      key_name: eu-central-1
      instance_tags:
        role: www
        ansible: True
      count_tag:
        role: www
      exact_count: 5
    register: ec2
  - name: Add hosts to group
    add_host: hostname={{ item.public_ip }} groups=just_created,eu-central-1
    with_items: ec2.instances
  - name: wait for SSH to come up
    wait_for: port=22 host={{ item.public_ip }} search_regex=OpenSSH
    with_items: ec2.instances

- name: Install nginx
  hosts: just_created
  tasks:
    - name: install nginx
      become: true
      apt: name=nginx state=present
